// Чек-лист приёмки квартиры (новостройка, без отделки/с отделкой — помечено).
// UZ — машинный черновик, на вычитку носителю. Номера норм проверить с инженером (см. TODO-NORMS.md).
// Формат: секция → пункты {id, ru, uz, how: как проверить, tool: что нужно}
const CHECKLIST = [
{ id: "docs", act: true, icon: "📑", ru: "До осмотра: документы", uz: "Koʻrikdan oldin: hujjatlar", items: [
 { id: "d1", ru: "Возьмите: паспорт, договор (ДДУ/КП), план квартиры из договора", uz: "Pasport, shartnoma va kvartira rejasini oling", how: "План нужен, чтобы сверять метраж и перегородки", how_uz: "Reja metrajni va toʻsiqlarni solishtirish uchun kerak", tool: "папка документов" },
 { id: "d2", ru: "Уточните заранее: дом введён в эксплуатацию (акт ввода)", uz: "Uy foydalanishga topshirilganini oldindan aniqlang", how: "Без ввода приёмка преждевременна — спросите номер/дату акта", how_uz: "Foydalanishga topshirilmagan boʻlsa, qabul qilish erta — dalolatnoma raqami va sanasini soʻrang", tool: "" },
 { id: "d3", ru: "Осмотр — только при дневном свете; заложите 1,5–2 часа", uz: "Koʻrikni kunduzi oʻtkazing, 1,5–2 soat ajrating", how: "Вечером дефекты стен/окон не видны", how_uz: "Kechqurun devor va deraza nuqsonlari koʻrinmaydi", tool: "" },
 { id: "d4", ru: "Не подписывайте акт приёма-передачи до конца осмотра", uz: "Koʻrik tugamaguncha qabul dalolatnomasini imzolamang", how: "Подпись без замечаний = «претензий не имею». Замечания вписываются В акт или в приложение к нему", how_uz: "Eʼtirozsiz imzo = «pretenziyam yoʻq». Eʼtirozlar dalolatnomaning OʻZIGA yoki unga ilovaga yoziladi", tool: "" },
 { id: "d5", ru: "Возьмите с собой: телефон с фонариком, зарядку (тест розеток), уровень/приложение-уровень, рулетку, лист бумаги, зажигалку (тяга), мел/стикеры", uz: "Fonarli telefon, quvvatlagich, nivelir (yoki nivelir ilovasi), ruletka, bir varaq qogʻoz, zajigalka (tortishni tekshirish uchun), boʻr yoki yelimli stiker oling", how: "Стикерами метьте каждый дефект и сразу фотографируйте", how_uz: "Har bir nuqsonni stiker bilan belgilang va darrov suratga oling", tool: "набор" },
]},
{ id: "entry", icon: "🚪", ru: "Входная дверь и тамбур", uz: "Kirish eshigi", items: [
 { id: "e1", ru: "Дверь открывается/закрывается без усилий, не задевает коробку", uz: "Eshik erkin ochilib-yopiladi, kesakiga tegmaydi", how: "Откройте на 45° — не должна сама распахиваться или закрываться (перекос)", how_uz: "45° ga oching — oʻzi ochilib yoki yopilib ketmasligi kerak (bu kesaki qiyshiqligini bildiradi)", tool: "" },
 { id: "e2", ru: "Замки и ключи: все комплекты работают, ручка не люфтит", uz: "Qulf va kalitlar ishlaydi, dastak boʻsh emas", how: "Проверьте каждый ключ из комплекта", how_uz: "Toʻplamdagi har bir kalitni tekshiring", tool: "" },
 { id: "e3", ru: "Уплотнитель по периметру, нет щелей (лист бумаги не вытягивается свободно)", uz: "Zichlagich butun, tirqish yoʻq (qogʻoz sinovi)", how: "Зажмите лист дверью в 4 точках — должен держаться", how_uz: "Qogʻozni eshik bilan 4 nuqtada qisib koʻring — ushlab turishi kerak", tool: "лист бумаги" },
 { id: "e4", ru: "Полотно без вмятин/царапин, наличники на месте", uz: "Eshik qanoti ezilmagan, nalichniklar joyida", how: "Осмотрите при боковом свете фонарика", how_uz: "Fonarni yon tomondan tushirib koʻring", tool: "фонарик" },
]},
{ id: "walls", icon: "🔨", ru: "Стены, потолок, пол", uz: "Devor, ship, pol", items: [
 { id: "w1", ru: "Стены: отклонение от вертикали в пределах нормы (ориентир: ≤ 10 мм на этаж высоты для черновой, меньше для чистовой)", uz: "Devorlar vertikaldan meʼyordan ortiq ogʻmagan", how: "Приложите уровень/телефон с приложением на 2 м. Норма требует не менее ПЯТИ измерений на каждые 50 м² (ШНҚ 3.04.01-21, табл. 10) — с двумя-тремя точками застройщику есть что ответить", how_uz: "Nivelirni yoki nivelir ilovasi oʻrnatilgan telefonni 2 m uzunlikda qoʻying. Meʼyor har 50 m² ga kamida BESHTA oʻlchashni talab qiladi (ShNQ 3.04.01-21, 10-jadval) — ikki-uchta nuqta bilan quruvchining javobi topiladi", tool: "уровень" },
 { id: "w2", ru: "Нет трещин (особенно сквозных и над проёмами), высолов, мокрых пятен", uz: "Yoriqlar, oq dogʻlar (shoʻra), nam dogʻlar yoʻq", how: "Трещину сфотографируйте с монетой для масштаба; мокрые углы = промерзание/протечка", how_uz: "Yoriqni masshtab uchun tanga bilan suratga oling; nam burchaklar = namlik oʻtishi", tool: "фонарик" },
 { id: "w3", ru: "Штукатурка/шпаклёвка без отслоений и пустот", uz: "Suvoq koʻchmagan, boʻshliqlar yoʻq", how: "Простучите костяшками: глухой «барабанный» звук = пустота (bухтит)", how_uz: "Barmoq boʻgʻini bilan urib koʻring: boʻgʻiq «baraban» tovushi = boʻshliq", tool: "" },
 { id: "w4", ru: "Потолок: без перепадов на стыках плит, трещин, следов протечек", uz: "Ship tekis, yoriq va oqma izlari yoʻq", how: "Особое внимание в санузле и у наружных стен", how_uz: "Hojatxonada va tashqi devorlar yonida alohida diqqat", tool: "фонарик" },
 { id: "w5", ru: "Пол/стяжка: без трещин, бухтения, перепадов (просвет под 2-м правилом: 2 мм под ламинат, паркет, линолеум и ПВХ; 4 мм под покрытия других видов)", uz: "Pol yoriqsiz, gʻovak emas, notekislik meʼyorda", how: "Пройдите всю площадь, слушая звук шагов; шарик/уровень покажет уклон. Норма требует не менее ДЕВЯТИ измерений ровности на каждые 50–70 м² готового пола и не менее пяти по стяжке (ШНҚ 3.04.01-21, табл. 29 и 19), а простукивание — по сетке 50×50 см", how_uz: "Butun maydonni aylanib chiqing, qadam tovushini tinglang; sharcha yoki nivelir qiyalikni koʻrsatadi. Meʼyor tayyor polning har 50—70 m² yuzasiga kamida TOʻQQIZTA oʻlchashni, stayjka boʻyicha kamida beshtasini talab qiladi (ShNQ 3.04.01-21, 29- va 19-jadvallar), urib koʻrish esa 50×50 sm toʻr boʻyicha", tool: "уровень/шарик" },
 { id: "w6", ru: "Метраж: сверьте фактическую площадь с договором (замер по 2 стенам каждой комнаты)", uz: "Maydonni shartnoma bilan solishtiring", how: "Отклонение площади — основание для перерасчёта по договору", how_uz: "Maydon chetlanishi shartnoma boʻyicha qayta hisob-kitob uchun asos", tool: "рулетка" },
]},
{ id: "windows", icon: "🌇", ru: "Окна и балкон", uz: "Derazalar va balkon", items: [
 { id: "o1", ru: "Створки открываются во всех режимах (распахивание/проветривание) без заеданий", uz: "Oynalar barcha rejimlarda ochiladi", how: "Проверьте каждую створку в квартире, включая балконный блок", how_uz: "Kvartiradagi har bir qanotni, balkon blokini ham qoʻshib tekshiring", tool: "" },
 { id: "o2", ru: "Стеклопакеты: без трещин, царапин, запотевания МЕЖДУ стёкол", uz: "Oyna paketlari yoriqsiz, ichida tuman yoʻq", how: "Конденсат внутри пакета = брак пакета, фиксируйте", how_uz: "Paket ichidagi kondensat = paket brakisi, qayd eting", tool: "фонарик" },
 { id: "o3", ru: "Нет продувания по периметру (лист бумаги/пламя зажигалки у стыков)", uz: "Chekkalaridan shamol oʻtmaydi", how: "Пламя/лист у рамы не должны отклоняться", how_uz: "Romga yaqin olov yoki qogʻoz ogʻmasligi kerak", tool: "зажигалка" },
 { id: "o4", ru: "Подоконники/откосы: ровные, без трещин, отлив снаружи закреплён", uz: "Deraza tokchasi tekis, tashqi suv qaytargich mahkam", how: "Налейте чуть воды на подоконник — не должна течь к раме", how_uz: "Deraza tokchasiga ozgina suv quying — romga oqib bormasligi kerak", tool: "бутылка воды" },
 { id: "o5", ru: "Балкон: остекление, перила закреплены, уклон пола ОТ двери, слив не в стену", uz: "Balkon oynasi va panjarasi mahkam, pol nishabi toʻgʻri", how: "Пошатайте перила рукой; проверьте примыкание пола к стене", how_uz: "Panjarani qoʻl bilan qimirlatib koʻring; polning devorga tutashishini tekshiring", tool: "" },
]},
{ id: "electric", icon: "🔌", ru: "Электрика", uz: "Elektr", items: [
 { id: "el1", ru: "Щиток: автоматы подписаны и держат нагрузку; если УЗО установлено — тест-кнопка срабатывает", uz: "Shitok: avtomatlar imzolangan; UZO oʻrnatilgan boʻlsa — «Test» tugmasi ishlaydi", how: "УЗО в Узбекистане рекомендуется, а не обязательно (ПУЭ разд. I п. 1.7.42; ҚМҚ 2.04.17-19 — так документ числится в фонде ТМСИТИ) — его отсутствие само по себе не дефект. Но если оно стоит и по кнопке «Тест» не выбивает — это замечание", how_uz: "Oʻzbekistonda HTQ (UZO) tavsiya etiladi, majburiy emas (EQQ I boʻlim, 1.7.4-band)", tool: "" },
 { id: "el2", ru: "Все розетки работают (проверка зарядкой), не выпадают из подрозетников", uz: "Barcha rozetkalar ishlaydi", how: "Пройдите с зарядкой телефона по каждой розетке", how_uz: "Telefon quvvatlagichi bilan har bir rozetkani aylanib chiqing", tool: "зарядка" },
 { id: "el3", ru: "Выключатели и точки освещения работают во всех комнатах", uz: "Vyklyuchatel va chiroq nuqtalari ishlaydi", how: "Возьмите патрон с лампочкой, если светильников нет", how_uz: "Chiroqlar yoʻq boʻlsa, lampochkali patron olib boring", tool: "лампочка" },
 { id: "el4", ru: "Звонок, домофон, слаботочка (интернет/ТВ вводы) — на месте", uz: "Eshik qoʻngʻirogʻi, domofon, internet kirishlari joyida", how: "Проверьте трубку домофона со связью с подъездом", how_uz: "Domofon trubkasini podyezd bilan aloqa qilib tekshiring", tool: "" },
]},
{ id: "plumbing", icon: "🚿", ru: "Сантехника и отопление", uz: "Santexnika va isitish", items: [
 { id: "p1", ru: "Стояки/разводка: нет подтёков, ржавчины, мокрых соединений", uz: "Quvurlarda oqish va zang yoʻq", how: "Проведите сухой салфеткой по соединениям — пятна покажут течь", how_uz: "Ulanish joylarini quruq salfetka bilan artib koʻring — dogʻlar oqishni koʻrsatadi", tool: "салфетка" },
 { id: "p2", ru: "Краны/вентили поворачиваются; счётчики воды установлены, пломбы на месте, перепишите номера и показания", uz: "Kranlar ishlaydi; hisoblagichlar plombalangan — raqamlarini yozib oling", how: "Фото счётчиков с номерами — в акт", how_uz: "Hisoblagichlarni raqamlari bilan suratga oling — dalolatnomaga", tool: "камера" },
 { id: "p3", ru: "Канализация: выпуски заглушены/без сколов, уклон гофры есть, запаха нет", uz: "Kanalizatsiya chiqishlari butun, hid yoʻq", how: "Если сантехника стоит — спустите воду, проверьте уход и запах", how_uz: "Santexnika oʻrnatilgan boʻlsa — suvni oqizing, ketishini va hidni tekshiring", tool: "" },
 { id: "p4", ru: "Гидроизоляция санузла: примыкания пол-стена без трещин (спросите акт скрытых работ)", uz: "Sanuzel gidroizolyatsiyasi — dalolatnoma soʻrang", how: "Акт на гидроизоляцию — в перечень запрошенных документов", how_uz: "Gidroizolyatsiya dalolatnomasini soʻraladigan hujjatlar roʻyxatiga qoʻshing", tool: "" },
 { id: "p5", ru: "Отопление: радиаторы закреплены, кронштейны не шатаются, краны/термоголовки на месте, нет следов подтёков (в сезон — все секции греют)", uz: "Radiatorlar mahkam, oqish izlari yoʻq, mavsumda qiziydi", how: "Вне сезона фиксируйте комплектность и крепёж; в сезон — температуру секций", how_uz: "Mavsumdan tashqarida toʻliqligini va mahkamlagichlarni qayd eting; mavsumda — seksiyalar haroratini", tool: "" },
]},
{ id: "vent", icon: "🌀", ru: "Вентиляция", uz: "Shamollatish", items: [
 { id: "v1", ru: "Тяга в вентканалах кухни и санузла (лист бумаги прилипает к решётке при закрытых окнах — приоткройте одно окно)", uz: "Oshxona va sanuzelda shamollatish tortadi (qogʻoz sinovi)", how: "Нет тяги/обратная тяга = дефект, влажность и плесень позже", how_uz: "Tortish yoʻq yoki teskari tortish = nuqson, keyinchalik namlik va mogʻor", tool: "лист бумаги" },
 { id: "v2", ru: "Решётки установлены, каналы не замусорены строительным мусором", uz: "Panjaralar oʻrnatilgan, kanallar toza", how: "Посветите фонариком в канал", how_uz: "Kanalga fonar bilan yorugʻlik tushiring", tool: "фонарик" },
]},
{ id: "final", act: true, icon: "✍️", ru: "Финал: фиксация и подписание", uz: "Yakun: hujjatlashtirish", items: [
 { id: "f1", ru: "Каждый дефект: стикер на место + фото общего плана и крупно (с масштабом — монета/рулетка)", uz: "Har bir nuqson: stiker + umumiy va yaqin plan foto", how: "Фото сразу нумеруйте по комнатам — пригодится для акта", how_uz: "Suratlarni darrov xonalar boʻyicha raqamlang — dalolatnoma uchun asqotadi", tool: "камера" },
 { id: "f2", ru: "Все замечания — письменно в акт осмотра/приложение к акту приёма-передачи, с подписью представителя застройщика", uz: "Barcha kamchiliklar yozma ravishda dalolatnomaga kiritiladi", how: "Формулировка: «Квартиру принимаю после устранения замечаний по приложению №1» — если решили не принимать сейчас", how_uz: "Ibora: «Kvartirani ... bandlar boʻyicha eʼtirozlar bartaraf etilgandan keyin qabul qilaman»", tool: "" },
 { id: "f3", ru: "Зафиксируйте срок устранения (по закону — 20 дней со дня требования; впишите конкретную дату) и способ связи", uz: "Bartaraf etish muddatini yozib qoʻying", how: "Без даты застройщик тянет; дата в документе = точка отсчёта претензии", how_uz: "Sanasiz quruvchi choʻzadi; hujjatdagi sana = pretenziya muddatining boshlanish nuqtasi", tool: "" },
 { id: "f4", ru: "Ключи/паспорта на счётчики, инструкции, гарантийные документы — заберите и сфотографируйте", uz: "Kalitlar, hisoblagich pasportlari, kafolat hujjatlarini oling", how: "Перечень полученного — в акт", how_uz: "Olingan narsalar roʻyxati — dalolatnomaga", tool: "" },
 { id: "f5", ru: "Если дефекты серьёзные — закажите «Акт осмотра + претензию» (кнопка ниже): оформим замечания со ссылками на нормы и подготовим претензию для самоподачи", uz: "Jiddiy nuqsonlar boʻlsa — «Dalolatnoma + pretenziya» xizmatini oling", how: "Фото дефектов у вас уже есть после этого чек-листа — этого достаточно", how_uz: "Nuqson suratlari shu cheklistdan keyin sizda allaqachon bor — shuning oʻzi yetarli", tool: "" },
]},
];

// --- Дополнительные разделы (вставляются перед финальным блоком «фиксация») ---
CHECKLIST.splice(CHECKLIST.length - 1, 0,
{ id: "finish", icon: "🎨", ru: "Если квартира с отделкой", uz: "Agar kvartira taʼmirli boʻlsa", items: [
 { id:"fn1", ru:"Межкомнатные двери: открываются без задевания, замки работают, наличники без щелей",
   uz:"Ichki eshiklar erkin ochiladi, qulflar ishlaydi, nalichniklar tirqishsiz",
   how:"Откройте каждую на 45° — не должна сама двигаться; проверьте каждый замок",
   how_uz:"Har birini 45° ga oching — oʻzi qimirlab ketmasligi kerak; har bir qulfni tekshiring", tool:"" },
 { id:"fn2", ru:"Обои или покраска: без пузырей и отслоений, стыки не расходятся, нет пятен и разнотона",
   uz:"Oboy yoki boʻyoq: pufaksiz, choklar ajralmagan, dog' yoʻq",
   how:"Смотрите вдоль стены при боковом свете фонарика — так видны волны и пятна",
   how_uz:"Fonarni yon tomondan tushirib, devor boʻylab qarang — shunda toʻlqin va dogʻlar koʻrinadi", tool:"фонарик" },
 { id:"fn3", ru:"Напольное покрытие: без вздутий, зазор у стен закрыт плинтусом, не скрипит",
   uz:"Pol qoplamasi: shishmagan, devor yonidagi tirqish yopilgan, gʻichirlamaydi",
   how:"Пройдите по всей площади, наступая на каждый участок",
   how_uz:"Butun maydonni har bir qismiga bosib aylanib chiqing", tool:"" },
 { id:"fn4", ru:"Плитка: швы ровные и одинаковые, под плиткой нет пустот, подрезка в углах аккуратная",
   uz:"Kafel: choklar tekis, ostida boʻshliq yoʻq, burchaklar toza",
   how:"Простучите костяшками — глухой звук значит пустота под плиткой",
   how_uz:"Barmoq boʻgʻini bilan urib koʻring — boʻgʻiq tovush kafel ostida boʻshliq borligini bildiradi", tool:"" },
 { id:"fn5", ru:"Сантехника установлена и работает: смеситель, слив, унитаз; под чашами нет течей",
   uz:"Santexnika oʻrnatilgan va ishlaydi; oqish yoʻq",
   how:"Пустите воду на 2–3 минуты, проведите сухой салфеткой по соединениям",
   how_uz:"Suvni 2–3 daqiqa oqizing, ulanish joylarini quruq salfetka bilan arting", tool:"салфетка" },
 { id:"fn6", ru:"Натяжной потолок: без провисаний и волн, углы и обходы труб выполнены аккуратно",
   uz:"Tortma ship: osilmagan, burchaklar va quvur atrofi toza",
   how:"Осмотрите под углом к источнику света",
   how_uz:"Yorugʻlik manbaiga qiya turib qarang", tool:"" },
 { id:"fn7", ru:"Встроенная мебель и кухня (если входят в договор): комплектность, фасады без сколов, ящики ходят",
   uz:"Oʻrnatilgan mebel va oshxona: butun, fasadlar shikastsiz, tortmalar ishlaydi",
   how:"Сверьте комплектацию с приложением к договору",
   how_uz:"Toʻplamni shartnoma ilovasi bilan solishtiring", tool:"договор" },
]},
{ id: "common", icon: "🏢", ru: "Подъезд, лифт, паркинг", uz: "Podyezd, lift, avtoturargoh", items: [
 { id:"cm1", ru:"Подъезд: отделка завершена, освещение работает, домофон на входе исправен",
   uz:"Podyezd: bezak tugagan, yoritish va domofon ishlaydi",
   how:"Это общее имущество — замечания по нему тоже вносятся в акт",
   how_uz:"Bu umumiy mulk — u boʻyicha kamchiliklar ham dalolatnomaga kiritiladi", tool:"" },
 { id:"cm2", ru:"Лифт работает, кабина без повреждений, в кабине есть табличка о вводе в эксплуатацию",
   uz:"Lift ishlaydi, kabina shikastsiz, foydalanishga ruxsat taxtachasi bor",
   how:"Прокатитесь до своего этажа и обратно",
   how_uz:"Oʻz qavatingizgacha borib qayting", tool:"" },
 { id:"cm3", ru:"Площадка для мусора оборудована, доступ к ней свободен",
   uz:"Chiqindi maydonchasi jihozlangan, kirish erkin", how:"", tool:"" },
 { id:"cm4", ru:"Паркинг или кладовая (если по договору): номер совпадает, доступ есть, размеры соответствуют",
   uz:"Avtoturargoh yoki ombor: raqami mos, kirish bor, oʻlchamlari toʻgʻri",
   how:"Замерьте место рулеткой и сверьте с приложением к договору",
   how_uz:"Joyni ruletka bilan oʻlchang va shartnoma ilovasi bilan solishtiring", tool:"рулетка" },
 { id:"cm5", ru:"Двор и подходы: покрытие уложено, нет открытых люков и строительного мусора",
   uz:"Hovli va yoʻlaklar: qoplama yotqizilgan, ochiq lyuk va qurilish chiqindisi yoʻq",
   how:"Сфотографируйте, если благоустройство не завершено — это тоже предмет замечаний",
   how_uz:"Obodonlashtirish tugamagan boʻlsa, suratga oling — bu ham kamchilik mavzusi", tool:"камера" },
]});
